Map<String, String> arabic = {
  "title1": "",
  "title2": "",
  "title3": "",
  "title4": "",
  "body1": "",
  "body2": "",
  "body3": "",
  "body4": "",
  "body5": "",
  "continuebutton": "التالي",
  "chooselanguage": "إختر لغتك المفضلة",
  "login": "تسجيل الدخول",
  "skipbutton": "تخطي",
  "english": "الإنجليزية",
  "arabic": "العربية",
  "signup": "إنشاء حساب",
  "createaccount": "ليس لديك حساب ؟",
  "location": "الموقع",
  "settings": "الإعدادات",
  "profile": "الملف الشخصي",
  "firstname1": "أدخل الاسم الأول",
  "firstname2": "الاسم الأول",
  "password2": "كلمة السر",
  "password1": "أدخل كلمة المرور",
  "signupbody": "أنشىء حسابك الآن للبدء",
  "lastname1": "أدخل الكنية",
  "laststname2": "الكنية",
  "phone2": "رقمك",
  "phone1": "أدخل رقمك",
  "email2": "البريد الإلكتروني",
  "email1": "أدخل البريد الإلكتروني",
  "homepage": "الرئيسية",
  "search": "ابحث",
  "favorite": "المفضلة",
  "categories": "الفئات",
  "additional": "معلومات إضافية",
  "welcome": "أهلا بك",
  "alreadyhaveaccount": "لديك حساب بالفعل ؟",
  "logintocontinue": "سجل دخولك للإكمال",
  "confirmpassword1": "أعد إدخال كلمة المرور",
  "confirmpassword2": "كلمة المرور",
  "myaccount": "حسابي الشخصي",
  "changelanguage": "تغيير اللغة",
  "darkmode": "الوضع الداكن",
  "logout": "تسجيل الخروج",
  "offices": "مكاتب",
  "lightmode": "الوضع الساطع",
  "choosemode": "اختر الوضع",
  "filter": "فلتر البحث",
  "confirm": "تأكيد",
  "warningbody": "هل تريد الخروج من التطبيق؟",
  "yes": "نعم",
  "no": "لا",
  "myfavorite": "المفضلة",
  "continuewithgoogle": "التسجيل عن طريق غوغل",
  "notifications": "الإشعارات",
  "hello": "مرحبا",
  "active": "مفعلة",
  "inactive": "متوقفة",
  "general": "عام",
  "account": "الحساب الشخصي",
  "helpcenter": "مركز الدعم",
  "appmode": "الوضع الداكن",
  "applaiedjobs": "الوظائف المقدم عليها",
  "report": "إبلاغ",
  "abouttheapp": "عن التطبيق",
  "language": "اللغة",
  "follow": "متابعة",
  "messages": "الرسائل",
  "reporttitle": "عنوان المشكلة",
  "reportdescription": "شرح المشكلة",
  "showmore": "عرض المزيد",
  "send": "إرسال",
  "employees": "الموظفين",
  "additionalinfo": "معلومات إضافية:",
  "editprofile": "تعديل الحساب",
  "yourreporthasbeensent": "تم إرسال الإبلاغ بنجاح",
  "sendingyourreport": "جاري إرسال الإبلاغ",
  "yourrequesthasbeensent": "تم إرسال طلبك",
  "message": "رسالة",
  "popularfreelancers": "أبرز المستقلين",
  "verifyingcode": "التحقق من البريد الالكتروني",
  "receivedcode": "أدخل الكود الذي استلمته",
  "errorsendingyourrequest": "لم يتم إرسال طلبك بنجاح",
  "changepassword": "تغيير كلمة المرور",
  "oldpassword1": "أدخل كلمة المرور الحالية",
  "oldpassword2": "كلمة المرور الحالية",
  "newpassword1": "أدخل كلمة المرور الجديدة",
  "newpassword2": "كلمة المرور الجديدة",
  "confirmnewpassword1": "تأكيد كلمة المرور",
  "confirmnewpassword2": "أعد إدخال كلمةالمرور",
  "resendthecode": "أعادة إرسال الرمز بعد ",
  "resend": "أعادةإرسال",
  "forgotyourpassword": "هل نسيت كلمة السر؟",
  "enteremail": "أدخل البريد الالكتروني لإرسال رمز التحقق",
  "resetyourpassword": "إعادة تعيين كلمو المرور",
  "emailverified": "تم التحقق",
  "enternewpassword": "أدخل كلمة المرور الجديدة",
  "reset": "أعادة تعيين",
  "sendingcodetoemail": "إرسال رمز التفعيل",
  "passworddoesntmatch": "كلمة المرور غير مطابقة",
  "pleaseaddanimage": "الرجاء إضافة صورة",
  "about": "حول",
  "savechanges": "حفظ التغييرات",
  "checkingcode": "التحقق من الرمز",
  "wrongcode": "رمز خطأ",
  "empty": "لا يمكن أن يكون فارغ",
  "warningbody2": "البريد الالكتروني أو رقم الهاتف موجود بالفعل",
  "less": "لايمكن أن يكون أقل من ",
  "more": "لا يمكن أن يكون أكثر من ",
  "letters": "أحرف",
  "opentowork": "جاهز للعمل",
  "pickupyourcounntry": "أختر بلدك",
  "errorloggingin": "حصل خطأ أثناء التسجيل",
  "wrongoldpassword": "كلمة المرور القديمة خاطئة",
  "passwordchangedsucessfully": "تم تغيير كلمة المرور بنجاح",
  "processingyourrequest": "جاري معالجة طلبك",
  "completeyourinfo": "أكمل معلوماتك",
  "existednumber": "رقم الهاتف موجود بالفعل",
  "post": "نشر",
  "yourpasswordhasbeenchanged": "تم تغيير كلمة المرور",
  "gender": "الجنس",
  "male": "ذكر",
  "female": "أنثى",
  "wronglogin": "خطأ في البريد الإلكتروني أو كلمة المرور",
  "youremailhasbeenverified": "تم تأكيد بريدك الإلكتروني",
  "emailisnotexisted": "البريد الإلكتروني غير موجود",
  "youremailisnotverified": "البريد الإلكتروني غير مؤكد\nهل تريد تأكيده؟",
  "rate": "التقييم",
  "yourdatahasbeensaved": "تم حفظ المعلومات بنجاح",
    "deletemyaccount":"حذف حسابي",
  "doyoureallywanttodeleteaccount":"هل تريد حقا حذف حسابك",
  "fillyourinformationtologin":""
};
