Map<String, String> english = {
  "title1": "Welcome to REstate",
  "title2": "Buy & sell",
  "title3": "Places near to you",
  "body1": "Find the ideal place according \nto your needs and expectaions",
  "body2": "Buy or sell any appartment, property, clinic or office you want",
  "body3":
      "Find the ideal place according \nto your needs and expectaions",
  "continuebutton": "Continue",
  "chooselanguage": "Choose your language",
  "skipbutton": "Skip",
  "english": "English",
  "arabic": "Arabic",
  "welcome": "Welcome to Sstate",
  "login": "Login",
  "signup": "Sign Up",
  "bio": "Bio",
  "bio2": "Enter a brief explanation about yourself",
  "createaccount": "Don't have an account ? ",
  "search": "Search",
  "homepage": "Home",
  "settings": "Settings",
  "profile": "Profile",
  "favorite": "Favorite",
  "location": "Location",
  "categories": "Categories",
  "addinfo": "Add your info to continue",
  "alreadyhaveaccount": "Already have an account ? ",
  "logintocontinue": "Login to continue",
  "firstname2": "First name",
  "firstname1": "",
  "password2": "Password",
  "password1": "Enter your password",
  "lastname1": "",
  "lastname2": "Last name",
  "phone1": "Enter your Phone",
  "phone2": "Phone",
  "email1": "Enter your email",
  "email2": "Email",
  "fillyourinformationtologin": "Fill your information to log in",
  "confirmpassword1": "Confirm your password",
  "confirmpassword2": "Password",
  "myaccount": "My Account",
  "changelanguage": "Change language",
  "darkmode": "Dark Mode",
  "logout": "Logout",
  "choosemode": "Choose mode",
  "filter": "Filter",
  "confirm": "Confirm",
  "warningbody": "Are you sure you want to exit?",
  "yes": "Yes",
  "no": "No",
  "myfavorite": "My Favorite",
  "notifications": "Notifications",
  "hello": "Hello",
  "active": "Active",
  "inactive": "In active",
  "general": "General",
  "account": "Account",
  "helpcenter": "Help center",
  "appmode": "App mode",
  "applaiedjobs": "Applied jobs",
  "warningbody2": "Email or phone number already existed",
  "report": "Report",
  "abouttheapp": "About the app",
  "language": "Language",
  "messages": "Messages",
  "lightmode": "Light mode",
  "reportdescription": "Report description",
  "reporttitle": "Report title",

  "additionalinfo": "Additional info:",
  "editprofile": "Edit profile",
  "verifyingcode": "Email verification",
  "receivedcode": "Please enter verification code sent to ",
  "errorsendingyourrequest": "Your request has not been sent",
  "changepassword": "Change password",
  "oldpassword1": "Enter old password",
  "oldpassword2": "Old password",
  "newpassword1": "Enter new password",
  "newpassword2": "new password",
  "confirmnewpassword1": "Confirm password",
  "confirmnewpassword2": "Confirm new password",
  "resendthecode": "Resend the code after ",
  "resend": "Resend",
  "forgotyourpassword": "Forgot your password?",
  "enteremail": "Enter your email adress to send the verification code",
  "resetyourpassword": "Reset your password",
  "emailverified": "Email verified",
  "reset": "Reset",
  "enternewpassword": "Enter your new password",
  "sendingcodetoemail": "Sending verification code ",
  "passworddoesntmatch": "Password doesn't match",
  "pleaseaddanimage": "Please add an image",
  "checkingcode": "Checking code",
  "wrongcode": "Wrong code",
  "empty": "Can't be empty",
  "less": "Can't be less than ",
  "more": "Can't be more than ",
  "letters": " letters",
  "errorloggingin": "Error while logging in",
  "processingyourrequest": "Processing request",
  "passwordchangedsucessfully": "Password changed successfully",
  "wrongoldpassword": "Wrong old password",
  "post": "Post",
  "projectlink": "Project link",
  "gender": "Gender",
  "male": "Male",
  "female": "Female",
  "Createanaccount":"Create an account so you can find your dream house",
  "setupyourprofile":"Setup your profile",
  "myposts":"My posts",
  "myappointments":"My appointments",
 
};
